#!/usr/bin/env python3
"""
Utility script to inspect the contents of the pickle file generated by main.py
"""

import pickle
import sys
import json
from typing import Dict, Any


def inspect_pickle_file(file_path: str):
    """Inspect and display information about the pickle file"""
    try:
        with open(file_path, 'rb') as f:
            documents = pickle.load(f)
        
        print(f"Pickle file: {file_path}")
        print(f"Total documents: {len(documents)}")
        
        if not documents:
            print("No documents found in the pickle file.")
            return
        
        # Display structure of first document
        print("\nFirst document structure:")
        first_doc = documents[0]
        for key, value in first_doc.items():
            value_type = type(value).__name__
            if isinstance(value, (list, dict)):
                if isinstance(value, list):
                    print(f"  {key}: {value_type} (length: {len(value)})")
                else:
                    print(f"  {key}: {value_type} (keys: {len(value)})")
            else:
                print(f"  {key}: {value_type} = {value}")
        
        # Show some statistics
        print(f"\nDocument statistics:")
        
        # Language distribution
        languages = {}
        old_question_ids = set()
        question_ids = set()
        
        for doc in documents:
            lang = doc.get('language', 'unknown')
            languages[lang] = languages.get(lang, 0) + 1
            
            if 'old_question_id' in doc:
                old_question_ids.add(doc['old_question_id'])
            
            if 'question_id' in doc:
                question_ids.add(doc['question_id'])
        
        print(f"  Unique old question IDs: {len(old_question_ids)}")
        print(f"  Unique question IDs: {len(question_ids)}")
        print(f"  Language distribution: {languages}")
        
        # Show sample document
        print(f"\nSample document (first one):")
        print(json.dumps(first_doc, indent=2, default=str))
        
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
    except pickle.UnpicklingError:
        print(f"Error: '{file_path}' is not a valid pickle file.")
    except Exception as e:
        print(f"Error reading pickle file: {e}")


def main():
    """Main entry point"""
    if len(sys.argv) != 2:
        print("Usage: python inspect_pickle.py <pickle_file_path>")
        sys.exit(1)
    
    pickle_file_path = sys.argv[1]
    inspect_pickle_file(pickle_file_path)


if __name__ == "__main__":
    main()
